### ISSUE TITLE
Invoke-IcingaCheckMSSQLHealth - Icinga Exception: The term 'Get-IcingaServiceCheckName' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Skeletitor** [Icinga/icinga-powershell-mssql#45]
Hi,

this error occures since the function 'Get-IcingaServiceCheckName' is moved to a private provider in powershell-plugins (https://github.com/Icinga/icinga-powershell-plugins/commit/ac2570874f866bfccd63456761675ed419800e57).

**Comment by LordHepipud** [comment]
Fixed with v1.10.0: https://github.com/Icinga/icinga-powershell-plugins/pull/308

**Comment by m4k5ym** [comment]
This is a great information but don't really solve my problem right now.

What do I have to do for a working implementation? At the moment this is used for a PoC and is considered as the way to go for our environment but if we don't get it to work it will be dropped as "not working, already fixed and release date out of range for testing".

This is no blame at all. Yours and your colleagues work on this framework is great and so bad needed. But we as user can't live with the fact that we rise our framework from 1.2.0 to 1.9.0 and some required / offered stuff is kinda bricked afterwards. It would be awesome if those dependencies like plugins will be more tested after core stuff changes.

**Comment by LordHepipud** [comment]
Thank you for the feedback. I fully understand this point. Our test environments are frequently updated and maintained to ensure such things will not happen in the future. A change was already made internally after investigating this issue, as this slipped through our test environment because of some configuration errors.

Icinga for Windows v1.10.0 will be released on August 9th 2022, which might be to late for the internal testing. It depends a little on your requirements and handling of patches.

If you are willing to modify the files locally for the testing at the moment, you could simply make the changes as done in this PR: https://github.com/Icinga/icinga-powershell-plugins/pull/308/commits/51b2ca6d30774c09c1d0b8d6e7d3ae78406096a5

There are only two files affected to make the function available to the public.

Would this be something considerable for your testing? Once these two files are updated, you would simply require to run `Publish-IcingaForWindowsComponent -Name 'plugins'`

**Comment by m4k5ym** [comment]
Thank you for your reply. I will try this and report back!
